services:
  app:
    image: ghcr.io/jaredkoontz/yt_feed:main
    container_name: yt_feed_app
    command: >
      gunicorn
      --conf app/yt_feed/conf/gunicorn_conf.py
      --bind 0.0.0.0:8000
      yt_feed.web_app:yt_feed_app
    environment:
      YOUTUBE_API_KEY: ${YT_KEY}
      DOMAIN: ${DOMAIN}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 512M
  nginx:
    image: ghcr.io/jaredkoontz/yt_feed_deploy:main
    container_name: yt_feed_edge
    ports:
      - "80:80"
    depends_on:
      - app